spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  ${POSTGRES_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    hikari:
      initialization-fail-timeout: 0
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: update