#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
#    username: {POSTGRES_USER}
#    password: {POSTGRES_PASSWORD}
#    hikari:
#      initialization-fail-timeout: 0
#jpa:
#  database-platform: org.hibernate.dialect.PostgresSQLDialect
#  generate-ddl: true
#  show-sql: true
#  hibernate:
#    ddl-auto: update